# Generated by Django 5.2.17 on 2026-10-01 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('approach_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('stroller_friendly', models.CharField(choices=[('YES', 'Yes'), ('PARTIALLY', 'Partially'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('family_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('family_notes', models.TextField(blank=True)),
                ('orientation', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crags', to='crags.area')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crags/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crags.crag')),
            ],
        ),
    ]
