# Generated by Django 5.2.17 on 2026-10-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='crag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crag',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
