# Generated by Django 5.2.17 on 2026-10-02 10:12

import crags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0002_alter_crag_options_crag_created_by_crag_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('CRAG', 'Fels'), ('BASE_AREA', 'Platz am Wandfuß'), ('APPROACH', 'Zustieg'), ('PARKING', 'Parkplatz'), ('OTHER', 'Sonstiges')], default='CRAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=crags.models.photo_upload_path),
        ),
    ]
