# Generated by Django 5.2.18 on 2026-10-09 09:58

import django.core.validators
from django.db import migrations, models


def migrate_stroller_characteristics(apps, schema_editor):
    Crag = apps.get_model("crags", "Crag")
    mapping = {
        "YES": "STROLLER_FRIENDLY",
        "PARTIALLY": "PARTIALLY_STROLLER_FRIENDLY",
        "NO": "NOT_STROLLER_FRIENDLY",
        "UNKNOWN": "STROLLER_UNKNOWN",
    }
    for old_value, new_value in mapping.items():
        Crag.objects.filter(stroller_friendly=old_value).update(
            approach_characteristics=[new_value]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0003_alter_photo_options_photo_category_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crag',
            old_name='family_rating',
            new_name='rating_ages_5_plus',
        ),
        migrations.AddField(
            model_name='crag',
            name='approach_characteristics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crag',
            name='guidebook',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='crag',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='parking',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crag',
            name='rating_ages_2_4',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='rating_babies',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(
            code=migrate_stroller_characteristics,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='crag',
            name='stroller_friendly',
        ),
        migrations.AlterField(
            model_name='crag',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('CRAG', 'Fels'), ('BASE_AREA', 'Platz am Wandfuß'), ('APPROACH', 'Zustieg'), ('PARKING', 'Parkplatz'), ('TERRAIN', 'Umgebung'), ('OTHER', 'Sonstiges')], default='CRAG', max_length=10),
        ),
    ]
