# Generated by Django 5.2.18 on 2026-10-09 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0004_remove_crag_family_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='crag',
            name='approach_assessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crag',
            name='base_assessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crag',
            name='rating_baby',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='rating_child',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='rating_toddler',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='crag',
            name='approach_features',
            field=models.ManyToManyField(blank=True, related_name='+', to='crags.feature'),
        ),
        migrations.AddField(
            model_name='crag',
            name='base_features',
            field=models.ManyToManyField(blank=True, related_name='+', to='crags.feature'),
        ),
    ]
