# Generated by Django 5.2.18 on 2026-10-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0006_seed_crag_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crag',
            name='rating_baby',
        ),
        migrations.RemoveField(
            model_name='crag',
            name='rating_child',
        ),
        migrations.RemoveField(
            model_name='crag',
            name='rating_toddler',
        ),
    ]
