# Generated by Django 5.2.18 on 2026-10-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0007_remove_crag_rating_baby_remove_crag_rating_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crag',
            name='approach_characteristics',
        ),
    ]
