# Generated by Django 5.2.18 on 2026-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0008_remove_crag_approach_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('CRAG', 'Crag'), ('BASE_AREA', 'Base area'), ('APPROACH', 'Approach'), ('PARKING', 'Parking'), ('TERRAIN', 'Surroundings'), ('OTHER', 'Other')], default='CRAG', max_length=10),
        ),
    ]
